export const products = [
    { id: 1, name: 'Sony WH-1000XM4 Headphones', price: 29990, image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2070&auto=format&fit=crop', description: 'Industry-leading noise canceling with Dual Noise Sensor technology. Next-level music with Edge-AI, co-developed with Sony Music Studios Tokyo.', category: 'Electronics', specs: { "Connectivity": "Bluetooth 5.0", "Battery Life": "30 hours", "Weight": "254g", "Driver Unit": "40mm" }, reviews: [{user: "Amit S.", rating: 5, comment: "Absolutely phenomenal sound quality and noise cancellation."},{user: "Priya K.", rating: 4, comment: "Great, but a bit pricey."}] },
    { id: 2, name: 'Apple Watch Series 9', price: 41900, image: 'https://images.unsplash.com/photo-1579586337278-35f4b7ebd37d?q=80&w=1974&auto=format&fit=crop', description: 'The most powerful chip in Apple Watch ever. A magical new way to use Apple Watch without touching the screen. A display that’s twice as bright.', category: 'Electronics', specs: { "Display": "Always-On Retina LTPO OLED", "Chip": "S9 SiP", "Water Resistance": "50 meters", "Sensors": "Blood Oxygen, ECG" }, reviews: [{user: "Rohan M.", rating: 5, comment: "The double tap feature is a game changer!"}] },
    { id: 3, name: 'Modern Leather Sofa', price: 59999, image: 'https://images.unsplash.com/photo-1540574163024-5735f35c235c?q=80&w=2070&auto=format&fit=crop', description: 'Upholstered in premium, top-grain leather with a sturdy kiln-dried hardwood frame. Perfect for lounging and entertaining.', category: 'Home Goods', specs: { "Material": "Genuine Leather", "Frame": "Kiln-dried hardwood", "Dimensions": "84\" W x 38\" D x 34\" H", "Seating Capacity": "3" }, reviews: [] },
    { id: 4, name: 'Levi\'s 501 Original Fit Jeans', price: 3599, image: 'https://images.unsplash.com/photo-1602293589930-4535a9a7c8c1?q=80&w=1974&auto=format&fit=crop', description: 'The iconic straight fit with the signature button fly. A blank canvas for self-expression since 1873.', category: 'Apparel', specs: { "Fit": "Straight", "Fabric": "100% Cotton Denim", "Rise": "Sits at waist", "Fly": "Button Fly" }, reviews: [{user: "Vikram R.", rating: 5, comment: "Classic for a reason. Perfect fit."}] },
    { id: 5, name: 'Canon EOS R6 Mark II Camera', price: 235000, image: 'https://images.unsplash.com/photo-1512790182537-5221952a2a73?q=80&w=2070&auto=format&fit=crop', description: 'A full-frame mirrorless camera that sets new standards for both photographers and filmmakers. 24.2MP sensor and 4K 60p video.', category: 'Electronics', specs: { "Sensor": "24.2MP Full-Frame CMOS", "Video": "4K 60p", "Autofocus": "Dual Pixel CMOS AF II", "Stabilization": "In-body 5-axis" }, reviews: [] },
    { id: 6, name: 'Nike Air Zoom Pegasus 40', price: 11895, image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2070&auto=format&fit=crop', description: 'A springy ride for every run. The Peg’s familiar, just-for-you feel returns to help you accomplish your goals.', category: 'Apparel', specs: { "Cushioning": "React foam with Zoom Air units", "Use": "Road running", "Weight": "289g (Men's size 10)", "Offset": "10mm" }, reviews: [] },
    { id: 7, name: 'Sujata Dynamix Mixer Grinder', price: 6290, image: 'https://placehold.co/600x400/6b7280/ffffff?text=Mixer', description: 'A powerful 900-watt motor with double ball bearings for efficiency, low maintenance and trouble-free running for years.', category: 'Home Goods', specs: { "Motor": "900 Watts", "Jars": "3 Stainless Steel Jars", "Speed": "3 Speed with Rotary action switch", "RPM": "22000 approx" }, reviews: [] },
    { id: 8, name: 'The Sleep Company SmartGRID Mattress', price: 24999, image: 'https://images.unsplash.com/photo-1585318090797-83a4385f7147?q=80&w=2070&auto=format&fit=crop', description: 'Patented SmartGRID Technology provides 2X more back support and ultimate comfort. Made from hyper-elastic polymer.', category: 'Home Goods', specs: { "Technology": "Patented SmartGRID", "Firmness": "Medium Firm", "Material": "Hyper-Elastic Polymer", "Warranty": "10 Years" }, reviews: [] },
];
